FROM ubuntu:20.04

RUN sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list
RUN apt-get update \
    && apt-get install -y git curl wget

RUN apt-get install -y python3-dev python3-pip vim

## Vim setup
RUN apt-get install -y exuberant-ctags ack-grep
RUN pip3 install --user pynvim flake8 pylint isort
RUN pip3 install --user -I jedi
RUN wget https://raw.githubusercontent.com/Lelp27/dockerimages/main/setting/fisa_vim.vimrc -O /root/.vimrc

## Python library
RUN pip3 install --user pandas matplotlib pysam

# clean
RUN apt-get update \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /usr/local/src/*

RUN echo "export LS_COLORS='di=00;36:fi=00;37'" >> ~/.bashrc

RUN mkdir /home/kun
WORKDIR /home/kun
