FROM ubuntu:20.04

RUN sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list
RUN apt-get update \
    && apt-get install -y git curl wget

RUN apt-get install -y python3-dev python3-pip vim

## Vim setup
RUN apt-get install -y exuberant-ctags ack-grep
RUN pip3 install pynvim flake8 pylint isort
RUN pip3 install -I jedi
RUN wget https://raw.github.com/fisadev/fisa-vim-config/v12.0.1/config.vim -O /root/.vimrc

## Python library
RUN pip3 install pandas matplotlib pysam


## Locales 굳이 한글로 안바꾸는게 낫다.
#RUN locale-gen ko_KR.UTF-8
#ENV LANG=ko_KR.UTF-8 LC_ALL=ko_KR.UTF-8
#bash export LANG=ko.KR_UTF-8

# clean
RUN apt-get update \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /usr/local/src/*

RUN echo "export LS_COLORS=\"di=00;36:fi=00;37\"" >> ~/.bashrc

RUN mkdir /home/kun
WORKDIR /home/kun
