highlight Comment term=bold ctermfg=2
highlight Special term=bold ctermfg=32
highlight Title term=bold ctermfg=32
highlight Directory term=bold ctermfg=32
highlight SpecialKey term=bold ctermfg=32
highlight Include term=bold ctermfg=63
highlight Define term=bold ctermfg=63
highlight Macro term=bold ctermfg=63
highlight PreCondit term=bold ctermfg=63
highlight Underlined term=bold ctermfg=63
highlight PreProc term=bold ctermfg=63
highlight shDeref term=bold ctermfg=63
highlight shDerefSimple term=bold ctermfg=63
highlight shPosnParm term=bold ctermfg=63
highlight shDerefSpecial term=bold ctermfg=63
highlight shDerefVar term=bold ctermfg=63
set fileformat=unix
set number
set t_Co=256
set bg=dark
set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set ruler
set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
set paste
set encoding=utf-8

filetype plugin indent on

call plug#begin('~/.vim/plugged')
Plug 'junegunn/seoul256.vim'
Plug 'frazrepo/vim-rainbow'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'davidhalter/jedi-vim'

call plug#end()

let g:airline#extensions#tabline#enabled = 1 " turn on buffer list
let g:airline_theme='hybrid'
let g:rainbow_active = 1
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
let g:seoul256_background = 233
colo seoul256
set laststatus=2 " turn on bottom bar
