FROM tjdrns27/vim:v0.2

## conda installation
RUN apt-get -qq update && apt-get -qq -y install ca-certificates
RUN curl -sSLk https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -u -bfp /usr/local
RUN /home/kun/miniconda3/bin/conda init \
    && rm -rf /tmp/miniconda.sh \
    && conda update conda

## conda packages
SHELL ["/bin/bash", "-c"]
RUN conda config --set auto_activate_base false \
    && conda config --set ssl_verify no \
    && conda config --add channels conda-forge \
    && conda config --add channels anaconda \
    && conda config --add channels bioconda

RUN conda install -c bioconda minimap2
RUN conda install -c bioconda samtools
RUN pip install nanopack medaka

# clean
RUN apt-get autoremove -y \
    && apt-get clean \
    && conda clean -a -y \
    && rm -rf /usr/local/src/*
