FROM tjdrns27/vim:v0.2

## pip module install
RUN pip install pysam nanopack medaka

## conda installation
RUN curl -sSLk https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -u -bfp /usr/local
RUN rm -rf /tmp/miniconda.sh \
    && conda update conda

## conda packages
SHELL ["/bin/bash", "-c"]
RUN conda config --set auto_activate_base false \
    && conda config --set ssl_verify no \
    && conda config --add channels conda-forge \
    && conda config --add channels bioconda \
    && conda config --add channels anaconda

RUN conda install -c bioconda minimap2
RUN conda install -c bioconda samtools
## write own librarys for python
RUN pip3 install --user pylint pynvim pandas pysam matplotlib
RUN conda update --all

# clean
RUN apt-get autoremove -y \
    && apt-get clean \
    && conda clean -a -y \
    && rm -rf /usr/local/src/*
