FROM ubuntu:20.04

RUN sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/source.list
RUN apt-get update \
    && apt-get install -y vim git curl wget locales

## Vim setup
RUN apt-get install -y python3-dev python3-pip exuberant-ctags ack-grep
RUN pip3 install pynvim flake8 pylint isort
RUN wget https://raw.github.com/fisadev/fisa-vim-config/v12.0.1/config.vim -O ~/.vimrc

## conda installation
RUN curl -sSLk https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -u -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh \
    && conda update conda

## conda packages
SHELL ["/bin/bash", "-c"]
RUN conda config --set ssl_verify no \
    && conda config --add channels conda-forge \
    && conda config --add channels anaconda \
    && conda config --add channels bioconda \
    && conda install pandas matplotlib scikit-learn pysam

RUN conda install minimap2 samtools
RUN conda install -c bioconda samtools medaka \
    && conda update --all
RUN pip install nanopack pysam

RUN echo "export LS_COLORS=\"di=00;36:fi=00;37\"" >> ~/.bashrc


RUN locale-gen ko_KR.UTF-8
ENV LANG=ko_KR.UTF-8 LC_ALL=ko_KR.UTF-8

# clean
RUN apt-get autoremove -y \
    && apt-get clean \
    && conda clean -a -y \
    && rm -rf /usr/local/src/*

RUN mkdir /home/kun
WORKDIR /home/kun
